// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "SceneviewInterface.h"

void SceneviewInterface::cb_Load_i(Fl_Button*, void*) {
  const char *strBack = fl_file_chooser("Scene name?", "*.sc", strSceneName.c_str() );

if ( strBack ) {
    sceneviewUI.readScene( strBack );
    strSceneName = strBack;
}
RedrawWindow();
}
void SceneviewInterface::cb_Load(Fl_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

void SceneviewInterface::cb_m_bLighting_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void SceneviewInterface::cb_m_bLighting(Fl_Check_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_m_bLighting_i(o,v);
}

void SceneviewInterface::cb_m_bInteractive_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void SceneviewInterface::cb_m_bInteractive(Fl_Check_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_m_bInteractive_i(o,v);
}

void SceneviewInterface::cb_m_bIBarHelp_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void SceneviewInterface::cb_m_bIBarHelp(Fl_Check_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_m_bIBarHelp_i(o,v);
}

void SceneviewInterface::cb_m_bIBar_i(Fl_Check_Button*, void*) {
  RedrawWindow();
}
void SceneviewInterface::cb_m_bIBar(Fl_Check_Button* o, void* v) {
  ((SceneviewInterface*)(o->parent()->user_data()))->cb_m_bIBar_i(o,v);
}

Fl_Double_Window* SceneviewInterface::make_window() {
  { m_sceneviewWindow = new Fl_Double_Window(310, 165, "Sceneview UI");
    m_sceneviewWindow->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(5, 5, 100, 25, "Load scene");
      o->callback((Fl_Callback*)cb_Load);
    } // Fl_Button* o
    { m_bLighting = new Fl_Check_Button(125, 5, 25, 25, "Lighting");
      m_bLighting->down_box(FL_DOWN_BOX);
      m_bLighting->value(1);
      m_bLighting->callback((Fl_Callback*)cb_m_bLighting);
    } // Fl_Check_Button* m_bLighting
    { m_bInteractive = new Fl_Check_Button(210, 5, 25, 25, "Interactive");
      m_bInteractive->down_box(FL_DOWN_BOX);
      m_bInteractive->value(1);
      m_bInteractive->callback((Fl_Callback*)cb_m_bInteractive);
    } // Fl_Check_Button* m_bInteractive
    { m_txtStatus = new Fl_Output(5, 60, 300, 100, "Status");
      m_txtStatus->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Output* m_txtStatus
    { m_bIBarHelp = new Fl_Check_Button(260, 30, 25, 25, "Help");
      m_bIBarHelp->down_box(FL_DOWN_BOX);
      m_bIBarHelp->callback((Fl_Callback*)cb_m_bIBarHelp);
    } // Fl_Check_Button* m_bIBarHelp
    { m_bIBar = new Fl_Check_Button(199, 30, 25, 25, "IBar");
      m_bIBar->down_box(FL_DOWN_BOX);
      m_bIBar->callback((Fl_Callback*)cb_m_bIBar);
    } // Fl_Check_Button* m_bIBar
    m_sceneviewWindow->end();
    m_sceneviewWindow->resizable(m_sceneviewWindow);
  } // Fl_Double_Window* m_sceneviewWindow
  return m_sceneviewWindow;
}

SceneviewInterface::SceneviewInterface() {
  m_sceneviewWindow = make_window();
  strSceneName = "../data/scenes/bujans_raquel.sc";
  sceneviewUI.setUI( this );
}

UIInterface * SceneviewInterface::getUI() {
  return &sceneviewUI;
}
